#!/usr/bin/with-contenv bash
export CUSTOM_PORT=$PORT
echo "[PORT = $PORT]"

# set SUBFOLDER to default if unset
if [ -z ${SUBFOLDER+x} ]; then
  SUBFOLDER="/"
fi

# just sleep if autostart is not enabled
if [ -z ${GUIAUTOSTART+x} ]; then
  echo "[guac-init] Auto start not set, application start on login"
  sleep infinity
# start abc session by sending a token to guacamole via websockets
else
  # make sure services are up
  until \
    $(true &>/dev/null </dev/tcp/localhost/3350) && \
    $(true &>/dev/null </dev/tcp/localhost/4822) && \
    $(true &>/dev/null </dev/tcp/localhost/${PORT}) &&
    $(true &>/dev/null </dev/tcp/localhost/3389)
  do
    sleep .5
  done
  echo "[guac-init] Auto start set, starting application"
  sleep 1
  # generate a token based on env vars
  cd /gclient
  TOKEN=$(node maketoken.js)
  websocat -q -n ws://localhost:${PORT}${SUBFOLDER}guaclite?token=${TOKEN}
  sleep infinity
fi
