#!/usr/bin/with-contenv bash
export CUSTOM_PORT=$PORT

gen_pass=$(openssl rand -hex 8)
echo "user = abc"
echo "password = $gen_pass"
echo "abc:$gen_pass" | chpasswd


cd /gclient || exit
HOME="/config" exec \
	s6-setuidgid abc node app.js
